language: php

php:

  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: hhvm
    - php: hhvm-nightly

script:
- ant

after_script:
  - php vendor/bin/coveralls
