language: php

php:

  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
- sudo pip install codecov

script:
- ant

after_script:
  - php bin/coveralls
  - codecov
