<?php if (isset($errors)): ?>
    Errors found:<br/>
    <?php foreach ($errors as $error): ?>
        <?=$error?><br/>
    <?php endforeach ?>
<?php endif ?>
<form method="post" action="/login">
    <table>
        <tr>
            <td>Username: </td>
            <td><input type="text" name="username" value="<?=$username?>"></td>
        </tr>
        <tr>
            <td>Password: </td>
            <td><input type="password" name="password" value="<?=$password?>"></td>
        </tr>
        <tr>
            <td colspan="2" align="right"><input type="submit" value="Login"></td>
        </tr>
    </table>
</form>