<?php if (isset($message)): ?>
    <?=$message?><br/><br/>
<?php endif ?>
<form method="post" action="/register">
    <table>
        <tr>
            <td>Username:</td>
            <td><input type="text" name="username" value="<?=$username?>"></td>
        </tr>
        <tr>
            <td>Password:</td>
            <td><input type="password" name="password"></td>
        </tr>
        <tr>
            <td>Password confirm:</td>
            <td><input type="password" name="passwordconfirm"></td>
        </tr>
        <tr>
            <td colspan="2" align="right"><input type="submit" value="Register"></td>
        </tr>
    </table>
</form>